name: konafa_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  firebase_auth: ^4.17.3
  firebase_messaging: ^14.7.10
  shared_preferences: ^2.2.2
  url_launcher: ^6.1.14
  flutter_localizations:
    sdk: flutter
  flutter:
    sdk: flutter
  firebase_core: ^2.24.2
  cloud_firestore: ^4.14.0
  http: ^1.1.2
  image_picker: ^1.0.7
  cached_network_image: ^3.3.0
  google_fonts: ^6.1.0
  flutter_lucide: ^1.2.0
  intl: ^0.19.0
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

