name: konafa_app
description: تطبيق كنافة بالقشطة
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^2.28.0
  cloud_firestore: ^4.16.0
  firebase_auth: ^4.17.3
  
  # UI & Design
  google_fonts: ^6.1.0
  cached_network_image: ^3.3.0
  
  # Utilities
  image_picker: ^1.0.4
  intl: ^0.18.1
  shared_preferences: ^2.2.2
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
